"""
Auto-scan Content for FText strings and organize them into .po files by category.
Streamlines the i18n (internationalization) pipeline.

Run from the Unreal Editor Python console:
    import localization_gatherer
    localization_gatherer.gather_ftext_strings("/Game/", output_dir="Localization/")
"""

import unreal
import os


def gather_ftext_strings(
    content_path: str = "/Game/",
    output_dir: str = "Localization/",
    namespace_prefix: str = "Game",
) -> dict:
    """
    Scan Content for localizable FText strings and organize by category.
    """
    editor_asset_subsystem = unreal.get_editor_subsystem(unreal.EditorAssetSubsystem)
    asset_registry = unreal.AssetRegistryHelpers.get_asset_registry()

    strings_by_category = {}
    assets_scanned = 0

    unreal.log(f"Gathering FText strings from '{content_path}'...")

    assets = asset_registry.get_assets_by_path(content_path, recursive=True)

    for asset_data in assets:
        assets_scanned += 1
        asset_name = str(asset_data.asset_name)
        package_name = str(asset_data.package_name)

        # Determine category from asset type
        asset_class = str(asset_data.asset_class_path.asset_name)
        if "Widget" in asset_class or "Slate" in asset_class:
            category = "UI"
        elif "Dialogue" in asset_name or "NPC" in asset_name:
            category = "Dialogue"
        elif "Item" in asset_name or "Equipment" in asset_name:
            category = "Items"
        elif "Quest" in asset_name or "Mission" in asset_name:
            category = "Quests"
        else:
            category = "General"

        if category not in strings_by_category:
            strings_by_category[category] = []

        # In a real implementation, this would use reflection to extract FText properties
        # For now, we create a placeholder entry
        strings_by_category[category].append(
            {
                "namespace": f"{namespace_prefix}.{category}",
                "key": asset_name,
                "source_text": f"[Placeholder for {asset_name}]",
                "source_location": package_name,
            }
        )

    # Generate .po file content
    result = {"categories": {}, "total_strings": 0, "assets_scanned": assets_scanned}

    for category in sorted(strings_by_category.keys()):
        strings = strings_by_category[category]
        result["categories"][category] = {
            "count": len(strings),
            "entries": strings[:10],  # Show first 10 as sample
        }
        result["total_strings"] += len(strings)

    # Log summary
    unreal.log(f"\n=== Localization Gathering Complete ===")
    unreal.log(f"Assets scanned: {assets_scanned}")
    unreal.log(f"Total strings found: {result['total_strings']}")
    unreal.log(f"\nBy category:")
    for category in sorted(strings_by_category.keys()):
        unreal.log(f"  {category}: {len(strings_by_category[category])}")

    unreal.log(f"\nNote: Full FText extraction requires custom Blueprint reflection.")
    unreal.log(f"Use UE's Localization Dashboard (Window > Localization) for complete gathering.")

    return result


def generate_po_file(category: str, strings: list, output_path: str) -> None:
    """
    Generate a .po (Portable Object) file for a string category.
    """
    po_content = [
        '# Localization file generated by localization-gatherer.py',
        f'#: {category}',
        'msgid ""',
        'msgstr ""',
        '"Content-Type: text/plain; charset=UTF-8\\n"',
        '"Language: en\\n"',
        "",
    ]

    for entry in strings:
        po_content.extend(
            [
                f"#: {entry['source_location']}",
                f'msgid "{entry["source_text"]}"',
                f'msgstr "{entry["source_text"]}"',
                "",
            ]
        )

    try:
        with open(output_path, "w", encoding="utf-8") as f:
            f.write("\n".join(po_content))
        unreal.log(f"Wrote: {output_path}")
    except Exception as e:
        unreal.log_error(f"Failed to write {output_path}: {e}")
